name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
      - run: make dev/setup
      - run: make build/release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: '.dev/build/release/*'
